const ROLES = {
    ADMIN: 'admin',
    CHAIRPERSON: 'chairperson',
    MANAGER: 'manager',
    LOANS_OFFICER: 'loans_officer',
    OFFICER: 'officer',
    TREASURER: 'treasurer'
};

const ALL = Object.values(ROLES);
const MEMBER_WRITE = [ROLES.ADMIN, ROLES.CHAIRPERSON];
const SAVINGS_WRITE = [ROLES.ADMIN, ROLES.CHAIRPERSON, ROLES.MANAGER, ROLES.TREASURER, ROLES.OFFICER];
const DEPOSIT_WRITE = [ROLES.ADMIN, ROLES.CHAIRPERSON, ROLES.TREASURER, ROLES.MANAGER];
const LOAN_WRITE = [ROLES.ADMIN, ROLES.CHAIRPERSON, ROLES.LOANS_OFFICER, ROLES.TREASURER, ROLES.OFFICER];
const LOAN_APPROVE = [ROLES.ADMIN, ROLES.CHAIRPERSON, ROLES.LOANS_OFFICER];
const STAFF_MANAGE = [ROLES.ADMIN, ROLES.CHAIRPERSON];
const INSURANCE_VIEW = [ROLES.ADMIN, ROLES.CHAIRPERSON, ROLES.LOANS_OFFICER, ROLES.TREASURER];

module.exports = {
    ROLES,
    ALL,
    MEMBER_WRITE,
    SAVINGS_WRITE,
    DEPOSIT_WRITE,
    LOAN_WRITE,
    LOAN_APPROVE,
    STAFF_MANAGE,
    INSURANCE_VIEW
};
