const ROLES = {
    ADMIN: 'admin',
    CHAIRMAN: 'chairman',
    LOAN_OFFICER: 'loan_officer',
    CASHIER: 'cashier',
    TREASURER: 'treasurer',
    OFFICER: 'officer'
};

const ALL = Object.values(ROLES);
const MEMBER_WRITE = [ROLES.ADMIN, ROLES.CHAIRMAN];
const SAVINGS_WRITE = [ROLES.ADMIN, ROLES.CHAIRMAN, ROLES.CASHIER, ROLES.TREASURER, ROLES.OFFICER];
const DEPOSIT_WRITE = [ROLES.ADMIN, ROLES.CHAIRMAN, ROLES.TREASURER, ROLES.CASHIER];
const LOAN_WRITE = [ROLES.ADMIN, ROLES.CHAIRMAN, ROLES.LOAN_OFFICER, ROLES.TREASURER, ROLES.OFFICER];
const LOAN_APPROVE = [ROLES.ADMIN, ROLES.CHAIRMAN, ROLES.LOAN_OFFICER];
const STAFF_MANAGE = [ROLES.ADMIN, ROLES.CHAIRMAN];
const INSURANCE_VIEW = [ROLES.ADMIN, ROLES.CHAIRMAN, ROLES.LOAN_OFFICER, ROLES.TREASURER];

module.exports = {
    ROLES,
    ALL,
    MEMBER_WRITE,
    SAVINGS_WRITE,
    DEPOSIT_WRITE,
    LOAN_WRITE,
    LOAN_APPROVE,
    STAFF_MANAGE,
    INSURANCE_VIEW
};
